name: Autograding Tests
on:
- push
- workflow_dispatch

permissions:
  contents: read
  statuses: write

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: (github.event_name != 'push' || github.event.head_commit.message != 'Initial commit')
    env:
      CI: true

      # These variables should go in the GitHub secrets, but since this is a public exercise
      # template, we want to make these available in any forks of the repository as well.
      # Therefore we are not using secrets but instead storing them here:
      JANE_USERNAME: jane.doe@example.com
      JANE_PASSWORD: ItWorksOnMyMac1!

      JOHN_USERNAME: john.doe@example.com
      JOHN_PASSWORD: AllTestsPass1!

      ALICE_USERNAME: alice@example.com
      ALICE_PASSWORD: '}3jc\xJnQ=E=+Q_y/%Hd311bW#6{_Oyj'

      BOB_USERNAME: bob@example.com
      BOB_PASSWORD: 'nUL9zA3q=Nt7\N,0?CL&c74U,Ic)0)dN'

    steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - name: Disable man-db auto-update (prevents apt-get hangs)
      run: sudo rm -f /var/lib/man-db/auto-update

    - name: Set up Node.js
      uses: actions/setup-node@v7
      with:
        node-version: 'lts/*'

    - name: Install Robot Framework and dependencies
      run: pip install -r requirements.txt
      timeout-minutes: 4

    - name: Install Chromium browser
      run: rfbrowser init chromium
      timeout-minutes: 2

    - name: Copy .env file
      run: cp .grading/.env.test .env

    - name: Run the example suite using autograder
      uses: ohjelmistokehitys/autograder@v0
      timeout-minutes: 4
      with:
        test_suite: ./.grading/config.json

    - uses: actions/upload-artifact@v7
      if: ${{ !cancelled() }}
      with:
        name: test-results
        path: test-results
        retention-days: 7
